INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('AB', 'Alberta', 'Alberta');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('BC', 'British Columbia', 'Colombie-Britannique');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('MB', 'Manitoba', 'Manitoba');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('NB', 'New Brunswick', 'Nouveau-Brunswick');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('NL', 'Newfoundland and Labrador', 'Terre-Neuve-et-Labrador');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('NS', 'Nova Scotia', 'Nouvelle-Écosse');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('NT', 'Northwest Territories', 'Territoires du Nord-Ouest');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('NU', 'Nunavut', 'Nunavut');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('ON', 'Ontario', 'Ontario');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('PE', 'Prince Edward Island', 'Île-du-Prince-Édouard');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('QC', 'Quebec', 'Québec');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('SK', 'Saskatchewan', 'Saskatchewan');
INSERT INTO PROVINCE (ID, NAME_EN, NAME_FR) VALUES ('YT', 'Yukon', 'Yukon');

INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('January 1', 'New Year’s Day', 'Jour de l’An');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Second Monday in February', 'Family Day', 'Fête de la famille');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Third Monday in February', 'Louis Riel Day', 'Journée Louis Riel');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Third Monday in February', 'Islander Day', 'Fête des Insulaires');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Third Monday in February', 'Family Day', 'Fête de la famille');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Third Monday in February', 'Heritage Day', 'Fête du Patrimoine');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('March 17', 'Saint Patrick’s Day', 'Jour de la Saint-Patrick');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Friday before Easter Day', 'Good Friday', 'Vendredi saint');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Monday after Easter Day', 'Easter Monday', 'Lundi de Pâques');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('April 23', 'Saint George’s Day', 'Jour de St. George');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Monday on or before May 24', 'National Patriots’ Day', 'Journée nationale des patriotes');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Monday on or before May 24', 'Victoria Day', 'Fête de la Reine');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('June 21', 'National Aboriginal Day', 'Journée nationale des Autochthones');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('June 24', 'Discovery Day / National Holiday', 'Journée découverte / Fête nationale du Québec / Saint-Jean-Baptiste');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('July 1', 'Canada Day', 'Fête du Canada');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('July 12', 'Orangemen’s Day', 'Fête des orangistes');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('First Monday in August', 'Civic Holiday', 'Premier lundi d’août');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('First Monday in August', 'Heritage Day', 'Fête du patrimoine');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('First Monday in August', 'New Brunswick Day', 'Jour de Nouveau Brunswick');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('First Monday in August', 'Natal Day', 'Jour de la Fondation');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Third Friday in August', 'Gold Cup Parade Day', 'Défilé de la Coupe d’or');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Third Monday in August', 'Discovery Day', 'Jour de la Découverte');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('First Monday in September', 'Labour Day', 'Fête du travail');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('Second Monday in October', 'Thanksgiving', 'Action de grâce');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('November 11', 'Armistice Day', 'Jour de l’Armistice');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('November 11', 'Remembrance Day', 'Jour du Souvenir');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('December 25', 'Christmas Day', 'Noël');
INSERT INTO HOLIDAY (DATE, NAME_EN, NAME_FR) VALUES ('December 26', 'Boxing Day', 'Lendemain de Noël');

INSERT INTO HOLIDAY_PROVINCE (HOLIDAY_ID, PROVINCE_ID) VALUES ((SELECT ID FROM HOLIDAY WHERE NAME_EN = 'New Year’s Day'), 'AB');
INSERT INTO HOLIDAY_PROVINCE (HOLIDAY_ID, PROVINCE_ID) VALUES ((SELECT ID FROM HOLIDAY WHERE NAME_EN = 'New Year’s Day'), 'ON');
